# Generated by Django 5.2 on 2025-04-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200)),
                ('render_name', models.CharField(max_length=200)),
                ('render_contact', models.CharField(max_length=200)),
                ('render_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
