# Generated by Django 5.2 on 2025-04-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lim_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='render_address',
            new_name='reader_address',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='render_contact',
            new_name='reader_contact',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='render_name',
            new_name='reader_name',
        ),
    ]
