# Generated by Django 5.2 on 2025-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lim_app', '0005_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
