# Generated by Django 5.2 on 2025-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lim_app', '0006_bookissue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='fine_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
