# Generated by Django 5.2 on 2025-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lim_app', '0007_book_price_bookissue_fine_rate_bookissue_is_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='damage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
